class Events:
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    ORDER_CREATED = "ORDER_CREATED"

    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    REFUND_CREATED = "REFUND_CREATED"

    AI_RECOMMENDATION = "AI_RECOMMENDATION"

    CAMPAIGN_GENERATED = "CAMPAIGN_GENERATED"