class Events:
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"

    ORDER_CREATED = "ORDER_CREATED"

    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    REFUND_CREATED = "REFUND_CREATED"

    AI_RECOMMENDATION = "AI_RECOMMENDATION"

    CAMPAIGN_GENERATED = "CAMPAIGN_GENERATED"
    AI_CAMPAIGN_CREATED = "AI_CAMPAIGN_CREATED"
    AI_BUNDLE_CREATED = "AI_BUNDLE_CREATED"

    CAMPAIGN_STATUS_UPDATED = "CAMPAIGN_STATUS_UPDATED"
    BUNDLE_STATUS_UPDATED = "BUNDLE_STATUS_UPDATED"
    AI_ACTION_EXECUTED = "AI_ACTION_EXECUTED"

